spring.application.name=sealeamon
spring.datasource.url=jdbc:mysql://leamon-mysql-a35044321.i.aivencloud.com:18032/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_BHkZXHxiLfkSMXgjpGK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect